// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvhjipio0y4QFtoiOiIlYiTn6_LTbHMQ',
    appId: '1:723963384686:web:5a92fb8ff9af898083a77f',
    messagingSenderId: '723963384686',
    projectId: 'my-final-project-8481b',
    authDomain: 'my-final-project-8481b.firebaseapp.com',
    storageBucket: 'my-final-project-8481b.firebasestorage.app',
    measurementId: 'G-4XC8VRTPR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5zl96KpQ0opzX-nJSpgWTL3dEbSDOKk',
    appId: '1:723963384686:android:0f5981a51c69f3c283a77f',
    messagingSenderId: '723963384686',
    projectId: 'my-final-project-8481b',
    storageBucket: 'my-final-project-8481b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhaj9f60F68cot1zOeS4VYb_CK04ytQ4',
    appId: '1:723963384686:ios:25669597fc175fe583a77f',
    messagingSenderId: '723963384686',
    projectId: 'my-final-project-8481b',
    storageBucket: 'my-final-project-8481b.firebasestorage.app',
    iosBundleId: 'com.example.haha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhaj9f60F68cot1zOeS4VYb_CK04ytQ4',
    appId: '1:723963384686:ios:25669597fc175fe583a77f',
    messagingSenderId: '723963384686',
    projectId: 'my-final-project-8481b',
    storageBucket: 'my-final-project-8481b.firebasestorage.app',
    iosBundleId: 'com.example.haha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvhjipio0y4QFtoiOiIlYiTn6_LTbHMQ',
    appId: '1:723963384686:web:abb20d4ee2363b9683a77f',
    messagingSenderId: '723963384686',
    projectId: 'my-final-project-8481b',
    authDomain: 'my-final-project-8481b.firebaseapp.com',
    storageBucket: 'my-final-project-8481b.firebasestorage.app',
    measurementId: 'G-XCR9XFRXD6',
  );
}
